// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionInfo } from "./QuestionInfo";
import type { QuestionPublication } from "./QuestionPublication";
import type { RoomInfo } from "./RoomInfo";

export type ClientMessage =
  | { kind: "Ok" }
  | { kind: "RoomInfo"; payload: RoomInfo }
  | { kind: "QuestionInfo"; payload: QuestionInfo }
  | { kind: "QuestionPublication"; payload: QuestionPublication }
  | { kind: "Error"; payload: string };
