// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QuestionState {
  title: string;
  options: Array<string>;
  answer: number | null;
}
