// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionId } from "./QuestionId";

export interface QuestionPublication {
  id: QuestionId;
  title: string;
  options: Array<string>;
  students: number;
}
