// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface QuestionModification { id: string, title: string | null, options: Array<string> | null, }