// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";

export interface RoomConnectInfo {
  room_name: string;
  connection_type: ConnectionType;
}
