// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CupColor } from "./CupColor";

export type WSMessage = { task: "RoomConnect", payload: string } | { task: "ChooseCup", payload: CupColor };