// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CupColor } from "./CupColor";
import type { PublishQuestion } from "./PublishQuestion";
import type { Question } from "./Question";
import type { QuestionAnswer } from "./QuestionAnswer";
import type { QuestionId } from "./QuestionId";
import type { QuestionModification } from "./QuestionModification";
import type { RoomConnectInfo } from "./RoomConnectInfo";

export type WSMessage =
  | { task: "RoomConnect"; payload: RoomConnectInfo }
  | { task: "ChooseCup"; payload: CupColor }
  | { task: "CreateQuestion"; payload: Question }
  | { task: "PublishQuestion"; payload: PublishQuestion }
  | { task: "DeleteQuestion"; payload: QuestionId }
  | { task: "ModifyQuestion"; payload: QuestionModification }
  | { task: "AnswerQuestion"; payload: QuestionAnswer };
